/* Ask Cyra's written evidence library, answered ON THIS DEVICE.
   The same red-flag check and plain-language answers the backend uses as its
   deterministic fallback (backend/src/modules/ai/tasks.js — keep the two in step).
   answerLocally() makes no network call; Ask only goes to Cyra's AI when the person
   has turned that on AND the library has no answer (see App.jsx runAsk). */

export const RED_FLAGS = /chest pain|can'?t breathe|short(ness)? of breath|faint|passed out|soak(ing|ed)? (a |one )?(pad|tampon)|every hour|hourly|bleeding (heavily|through)|large clots|severe headache|vision (change|blur)|suicid|kill myself|self[- ]harm|end my life|(no|less|reduced) (fetal |baby )?move|baby (isn'?t|is not|stopped) moving|fever (over|above|of) (39|102|103)|severe (pain|swelling)|seizure|collapsed/i;
export const LIBRARY = [
  { re: /hormone (replacement )?therapy|\bhrt\b|\bmht\b|estrogen patch|cancer risk/i, answer: "Hormone therapy is the most effective treatment for hot flashes and night sweats, and for most healthy women who start it before 60 or within ten years of their last period, the benefits outweigh the risks. The cancer question is more specific than the headlines: in the big Women's Health Initiative trial, estrogen taken alone did not raise breast cancer risk, while estrogen plus a progestogen raised it slightly after several years of use — a small absolute change, similar in size to other everyday factors. Your own history matters a lot: prior breast cancer, blood clots, stroke, or liver disease change the picture. The honest answer is that this is a personal risk-benefit decision, best made with a clinician who knows your history.", source_note: "The Menopause Society 2022 Hormone Therapy Position Statement; NICE menopause guideline NG23; Women's Health Initiative follow-up studies.", ask: "Given my history, am I a candidate for hormone therapy — and if so, estrogen-only or combined?" },
  { re: /non[- ]?hormonal|without hormones|ssri|fezolinetant|hot flash|night sweat/i, answer: "Hot flashes and night sweats are very treatable, and hormone therapy isn't the only route. Non-hormonal options with real evidence include certain antidepressants used at low doses (SSRIs and SNRIs), gabapentin, oxybutynin, and a newer class — neurokinin-3 receptor antagonists such as fezolinetant — that acts directly on the brain's temperature control. Cognitive behavioral therapy and clinical hypnosis also reduce how much flashes disrupt life. Supplements like black cohosh and soy isoflavones have mixed or weak evidence. Bringing a count of your flashes per week to a visit makes the conversation concrete.", source_note: "The Menopause Society 2023 Nonhormone Therapy Position Statement; NICE NG23; Cochrane reviews of non-hormonal treatments for vasomotor symptoms.", ask: "Which non-hormonal option fits me best given my other medications and health history?" },
  { re: /sleep|insomnia|wake up|can'?t fall asleep/i, answer: "Sleep problems around hormonal change are common, and the first-line treatment isn't a pill: cognitive behavioral therapy for insomnia (CBT-I) has the strongest evidence, works as well as sleep medication in the short term and better in the long term, and has no side effects. Night sweats that wake you are a separate, treatable problem — fixing them often fixes the sleep. Sleeping pills are generally a short-term bridge, not a plan. Tracking which nights are rough alongside your symptoms helps a clinician see the pattern.", source_note: "American Academy of Sleep Medicine clinical guideline for chronic insomnia; The Menopause Society; NICE NG23.", ask: "Could I be referred for CBT-I, and are my night sweats part of why I'm not sleeping?" },
  { re: /cramp|period pain|dysmenorrhea|endometriosis/i, answer: "Period cramps come from prostaglandins — chemicals that make the uterus contract — which is why anti-inflammatory painkillers and continuous low-level heat both genuinely work, with good trial evidence behind each. Hormonal contraception is another well-evidenced option for people who want it. The line to watch: pain that regularly stops you from working, studying, or getting out of bed is not something to push through. Endometriosis and adenomyosis are common causes of pain like that, and they typically take years to diagnose largely because people are told it's normal.", source_note: "ACOG Committee Opinion on dysmenorrhea and endometriosis in adolescents; Cochrane reviews of NSAIDs and of heat for dysmenorrhea; NICE NG73 endometriosis guideline.", ask: "My pain reaches this level on this many days a month — could it be endometriosis, and how would we check?" },
  { re: /heavy (period|bleed|flow)|menorrhagia|clots|flooding|anemi/i, answer: "Heavy periods are defined by what they do to your life, not a number: soaking a pad or tampon every hour, passing clots bigger than a coin, bleeding for more than seven days, or needing to change protection overnight. It's common, it's treatable, and the first thing a clinician checks is iron, because heavy bleeding is the leading cause of anemia in women. Treatment options to ask about include tranexamic acid taken only on heavy days, hormonal options including the hormonal IUD, and investigation of causes like fibroids or polyps. Bleeding that is suddenly much heavier than your normal, with dizziness or breathlessness, needs same-day care.", source_note: "ACOG Practice Bulletin on heavy menstrual bleeding; NICE NG88 heavy menstrual bleeding guideline; Cochrane reviews of tranexamic acid.", ask: "Could we check a blood count and iron, and which treatment options fit my situation?" },
  { re: /exercise|workout|run(ning)?|lift|yoga|safe to .* (pregnan|trimester)/i, answer: "For an uncomplicated pregnancy, exercise is recommended, not just allowed: the guidance is about 150 minutes of moderate activity a week, continued through all three trimesters, and it lowers the risk of gestational diabetes, excess weight gain, and some pregnancy complications. Walking, swimming, stationary cycling, prenatal yoga, and strength training are all considered safe. Things to avoid: contact sports, activities with a real fall risk, hot yoga, scuba diving, and lying flat on your back for long periods after the first trimester. Stop and call your provider for bleeding, regular painful contractions, fluid leaking, dizziness, chest pain, or calf pain.", source_note: "ACOG Committee Opinion 804, Physical Activity and Exercise During Pregnancy and the Postpartum Period; Canadian Guideline for Physical Activity throughout Pregnancy.", ask: "Is there anything about my pregnancy that changes the standard exercise advice?" },
  { re: /odor|smell|discharge|bacterial vaginosis|\bbv\b|yeast|thrush|itch/i, answer: "A fishy odor, especially with thin grey or white discharge, is the classic sign of bacterial vaginosis — the most common vaginal condition, caused by a shift in the normal bacteria rather than anything you did. It's treated with a short course of antibiotics, and over-the-counter yeast treatments won't fix it. Thick white discharge with itching points more toward yeast, which can be treated over the counter, but a first episode or repeated episodes should be confirmed. Healthy vaginas have a scent that changes across the cycle, and douching makes infections more likely, not less. Green, frothy, or bloody discharge, or pain with it, deserves a proper look.", source_note: "CDC Sexually Transmitted Infections Treatment Guidelines (bacterial vaginosis and vulvovaginal candidiasis); ACOG FAQ on vaginitis.", ask: "Could you test the discharge so we treat the right thing the first time?" },
  { re: /fertil|ovulat|conceive|get pregnant|trying for a baby|lh (test|strip)/i, answer: "The fertile window is roughly the five days before ovulation plus the day itself, because sperm can wait several days but an egg lasts less than a day. Apps estimate ovulation from your past cycle lengths, so the estimate is only as good as your regularity — a range, not a day. Ovulation predictor kits detect the hormone surge a day or so before ovulation; basal body temperature confirms it happened, but only after the fact. Sex every one to two days through the window is as effective as any precise timing. If you've been trying for a year — or six months if you're over 35 — that's the standard point to ask for an evaluation, for both partners.", source_note: "ACOG FAQ on evaluating infertility; American Society for Reproductive Medicine committee opinion on optimizing natural fertility; Cochrane review of timed intercourse.", ask: "Based on how long we've been trying and my age, is it time for a fertility evaluation?" },
  { re: /irregular|cycle (length|vary|chang)|perimenopaus|am i in (peri)?menopause|skipp(ed|ing) period/i, answer: "Cycles that start varying by a week or more from one to the next are the clearest early sign of the menopause transition — it's literally the marker doctors use to stage it. Perimenopause can last several years and is diagnosed from your pattern and symptoms, not a blood test, because hormone levels swing day to day. Irregular cycles under 40 can have other causes worth checking, including thyroid problems and polycystic ovary syndrome. A record of your cycle lengths and symptoms is more useful at a visit than any single lab value, and treatment for symptoms doesn't have to wait until periods stop.", source_note: "STRAW+10 staging criteria for reproductive aging; The Menopause Society; NICE NG23.", ask: "My cycles have ranged this widely — could this be perimenopause, and what should we check to rule out other causes?" },
  { re: /tired|fatigue|exhaust|no energy|thyroid|iron|vitamin d/i, answer: "Feeling wiped out for weeks is a symptom worth investigating rather than normalizing. Three common, easily tested causes show up as fatigue: an underactive thyroid, iron-deficiency anemia (very common with heavy periods), and low vitamin D. Each is a simple blood test, and each is treatable. Poor sleep and mood changes around hormonal transitions also drain energy, so a sleep pattern alongside your fatigue scores gives a clinician something concrete. Asking for the tests by name tends to work better than saying \"I'm just tired.\"", source_note: "American Thyroid Association guidelines; ACOG guidance on anemia in women; NICE guidance on tiredness and vitamin D deficiency.", ask: "Could we check my thyroid, a full blood count with iron studies, and vitamin D?" },
];

const URGENT = "What you're describing can be a sign of something that needs to be checked today, not researched. Please contact your provider now, or go to urgent care or an emergency department — and if you are thinking about harming yourself, call or text 988 (US) or your local crisis line. You are not overreacting by asking.";
const UNMATCHED = "Cyra's written library doesn't have an answer for that one yet. Rather than guess, here's the honest route: write the question down exactly as you asked it here and bring it to your next visit — clinicians answer specific questions far better than vague ones. If it's about a symptom that is new, severe, or getting worse, don't wait for the appointment.";

/** question → { answer, source_note, ask_your_doctor, urgent, matched }. Pure; runs on this device. */
export function answerLocally(question) {
  const q = String(question || "").trim().slice(0, 500);
  if (RED_FLAGS.test(q)) return { answer: URGENT, source_note: null, ask_your_doctor: null, urgent: true, matched: true };
  const hit = LIBRARY.find((t) => t.re.test(q));
  if (hit) return { answer: hit.answer, source_note: hit.source_note, ask_your_doctor: hit.ask, urgent: false, matched: true };
  return { answer: UNMATCHED, source_note: null, ask_your_doctor: q || null, urgent: false, matched: false };
}
